## Reading Files into Python

In [0]:
# importing libraries
import pandas as pd

In [0]:
#importing data
data = pd.read_csv('churn_prediction.csv')

In [0]:
#first 5 instances using "head()" function
data.head()

   customer_id  vintage  age  ... previous_month_balance  churn last_transaction
0            1     3135   66  ...                1458.71      0       2019-05-21
1            2      310   35  ...                8787.61      0       2019-11-01
2            4     2356   31  ...                5070.14      0              NaT
3            5      478   90  ...                1669.79      1       2019-08-06
4            6     2531   42  ...                1677.16      1       2019-11-03

[5 rows x 21 columns]

In [0]:
#last 5 instances using "tail()" function
data.tail()

       customer_id  vintage  ...  churn last_transaction
28377        30297     1845  ...      0       2019-10-22
28378        30298     4919  ...      0       2019-12-17
28379        30299      297  ...      1       2019-12-31
28380        30300     2585  ...      0              NaT
28381        30301     2349  ...      1       2019-11-02

[5 rows x 21 columns]

In [0]:
#finding out the shape of the data using "shape" variable: Output (rows, columns)
data.shape

(28382, 21)

In [0]:
#Printing all the columns present in data
data.columns

Index(['customer_id', 'vintage', 'age', 'gender', 'dependents', 'occupation',
       'city', 'customer_nw_category', 'branch_code', 'current_balance',
       'previous_month_end_balance', 'average_monthly_balance_prevQ',
       'average_monthly_balance_prevQ2', 'current_month_credit',
       'previous_month_credit', 'current_month_debit', 'previous_month_debit',
       'current_month_balance', 'previous_month_balance', 'churn',
       'last_transaction'],
      dtype='object')

In [0]:
data.dtypes

customer_id                         int64
vintage                             int64
age                                 int64
gender                             object
dependents                        float64
occupation                         object
city                              float64
customer_nw_category                int64
branch_code                         int64
current_balance                   float64
previous_month_end_balance        float64
average_monthly_balance_prevQ     float64
average_monthly_balance_prevQ2    float64
current_month_credit              float64
previous_month_credit             float64
current_month_debit               float64
previous_month_debit              float64
current_month_balance             float64
previous_month_balance            float64
churn                               int64
last_transaction                   object
dtype: object